{
    'name': 'BiziShip',
    'version': '17.0.2.1.1',
    'category': 'Sales',
    'summary': 'AI-Powered LTL & FTL Quoting & Automated Freight Procurement',
    'description': """
        The ultimate shipping companion for Odoo. Supercharge your logistics
        with instant Mega-Search LTL and FTL quoting, real-time rate shopping, and
        AI-driven BOL extraction to optimize your bottom line.
    """,
    'author': 'BiziShip',
    'website': 'https://www.biziship.ai',
    'support': 'zeev@biziship.ai,avner@biziship.ai',
    'images': ['static/description/banner.png'],
    'depends': ['base', 'sale'],
    'external_dependencies': {
        'python': ['requests', 'PyPDF2'],
    },
    'data': [
        'security/ir.model.access.csv',
        'data/accessorial_data.xml',
        'views/res_config_settings_views.xml',
        'wizards/biziship_bol_wizard_views.xml',
        'wizards/biziship_quote_confirm_wizard_views.xml',
        'wizards/biziship_booking_warning_wizard_views.xml',
        'wizards/biziship_freight_quote_wizard_views.xml',
        'wizards/biziship_auth_wizard_views.xml',
        'wizards/biziship_save_freight_wizard_views.xml',
        'wizards/biziship_load_freight_wizard_views.xml',
        'wizards/biziship_tracking_wizard_views.xml',
        'wizards/biziship_address_history_wizard_views.xml',
        'wizards/biziship_not_connected_wizard_views.xml',
        'wizards/biziship_logout_wizard_views.xml',
        'wizards/biziship_quotes_report_wizard_views.xml',
        'wizards/biziship_email_quotes_simple_wizard_views.xml',
        'wizards/biziship_email_quotes_confirm_wizard_views.xml',
        'views/sale_order_views.xml',
        'views/res_users_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'biziship/static/src/js/sale_order_auto_tab.js',
            'biziship/static/src/js/biziship_tab_handler.js',
            'biziship/static/src/js/biziship_places_autocomplete.js',
            'biziship/static/src/js/biziship_commodity_autocomplete.js',
            'biziship/static/src/js/biziship_nmfc_favorites.js',
            'biziship/static/src/js/biziship_zip_input.js',
            'biziship/static/src/js/biziship_ref_copy.js',
            'biziship/static/src/js/biziship_hours_picker.js',
            'biziship/static/src/js/biziship_email_chips.js',
            'biziship/static/src/js/biziship_references.js',
            'biziship/static/src/xml/biziship_commodity_templates.xml',
            'biziship/static/src/xml/biziship_nmfc_favorites.xml',
            'biziship/static/src/xml/biziship_hours_picker.xml',
            'biziship/static/src/xml/biziship_email_chips.xml',
            'biziship/static/src/xml/biziship_references.xml',
            'biziship/static/src/css/biziship_modern.css',
        ],
    },
    'application': True,
    'license': 'LGPL-3',
}
